# Generated by Django 5.0.2 on 2024-02-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0003_alter_user_managers_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
