# Generated by Django 5.0.4 on 2024-05-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offence_description', models.TextField()),
                ('location', models.TextField()),
                ('nearest_police_station', models.TextField()),
                ('vehicle_number', models.TextField(null=True)),
                ('no_of_offendents', models.IntegerField()),
                ('accused', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
            ],
        ),
    ]
